name: Hic Sunt
author: Kenneth Pouncey
description: Some description
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: Dracones
outputs:
  time:
    description: 'The greeting time'
runs:
  using: "node12"
  main: "dist/index.js"