name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:17-alpine3.14
    steps:
      - name: Log Node version
        run: |
          node -v
          cat /etc/os-release
      - uses: actions/checkout@v2.4.0
      - name: Run a ascript
        uses: docker://node:17-alpine3.14
        with:
          entrypoint: ./script.sh
          args: "some string"
  deno-docker:
    runs-on: ubuntu-latest
    container: 
      image: denoland/deno:alpine-1.17.2
    steps:
      - name: Log Deno version
        run: |
          deno --version
          cat /etc/os-release
      - uses: actions/checkout@v2.4.0
      - name: Run a ascript
        uses: docker://denoland/deno:alpine-1.17.1
        with:
          entrypoint: ./script.sh
          args: "some string"      