name: Docker

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      working_directory: ./api
      DOCKER_PROJECT_NAME: ${{ github.event.repository.name }}
      DOCKER_PROJECT_NAME_API: ${{ github.event.repository.name }}_api
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Define short sha variable
        run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
        
      # Signin to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build docker image
        run: |
          cd api
          docker image build -t env.DOCKER_PROJECT_NAME_API:$SHORT_SHA .
          
      # - name: Push to docker hub
      #   run: |
      #     docker tag ${{ env.DOCKER_PROJECT_NAME_API }}:${{ env.SHORT_SHA }} ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_PROJECT_NAME_API }}:${{ env.SHORT_SHA }}
      #     docker tag ${{ env.DOCKER_PROJECT_NAME_API }}:${{ env.SHORT_SHA }} ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_PROJECT_NAME_API }}:latest
      #     docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_PROJECT_NAME_API }}:${{ env.SHORT_SHA }}
      #     docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_PROJECT_NAME_API }}:latest
