name: Docker

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Define short sha variable
        run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
        
      # Signin to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build docker image
        run: |
          cd api
          docker image build -t deno-test-actions:$SHORT_SHA .
          
      - name: Push to docker hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:$SHORT_SHA
