name: Matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, window-latest]
        node_version: [6,8,10]
      #max-parallel: 2
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: node -v
      - uses: denoland/setup-deno@v1
        with:
          node-version: ${{ matrix.node_version }}
  deno-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, window-latest]
        deno_version: [1.17.0, 1.17.1]
      #max-parallel: 2
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log deno version
        run: deno --version
      - uses: actions/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno_version }}          