name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest] # [macos-latest, ubuntu-latest, windows-latest]
        #deno_version: [1.17.1, 1.17.2]
        deno_version: [~1.17, ~1.18]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      
      # Setup deno version
      - name: Use Deno Version ${{ matrix.deno_version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno_version }}

      - name: Test
        env:
          HOSTNAME: smtp.gmail.com
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          MAIL_TO_USER: ${{ secrets.MAIL_USER }}
        run: deno run --allow-net --allow-env ./test.ts
